import {
  GetDashboardSummaryResponse,
  GetDashboardTournamentsResponseItem,
  ListGamesResponseItem,
  ListLeaderboardsResponseItem,
  ListTournamentsResponseItem,
  RegisterForTournamentResponse,
  GetTournamentResponse,
} from "@workspace/api-zod";
import type {
  DashboardSummary,
  Game,
  LeaderboardEntry,
  RegisteredTournament,
  Registration,
  TournamentDetail,
} from "@workspace/api-zod";

export type { Registration };
export type Tournament = TournamentDetail;

export const games: Game[] = [
  {
    id: "bgmi",
    name: "Battlegrounds Mobile India",
    slug: "bgmi",
    shortName: "BGMI",
    description: "Squad up for tactical battle royale tournaments.",
    color: "#ffb547",
    status: "ACTIVE",
    playerCount: 12480,
  },
  {
    id: "free-fire",
    name: "Free Fire",
    slug: "free-fire",
    shortName: "Free Fire",
    description: "Fast rounds, sharp aim, big local rivalries.",
    color: "#ff5c73",
    status: "ACTIVE",
    playerCount: 9340,
  },
  {
    id: "ludo",
    name: "Ludo King",
    slug: "ludo",
    shortName: "Ludo",
    description: "Classic board play with a competitive twist.",
    color: "#8f7cff",
    status: "ACTIVE",
    playerCount: 5120,
  },
  {
    id: "valorant",
    name: "Valorant",
    slug: "valorant",
    shortName: "Valorant",
    description: "Precision, teamwork, and clutch moments.",
    color: "#6a7cff",
    status: "COMING_SOON",
    playerCount: 0,
  },
  {
    id: "cod-mobile",
    name: "Call of Duty Mobile",
    slug: "cod-mobile",
    shortName: "COD Mobile",
    description: "Competitive mobile FPS tournaments are on the way.",
    color: "#70d6bd",
    status: "COMING_SOON",
    playerCount: 0,
  },
];

export const tournaments: TournamentDetail[] = [
  {
    id: "wl-bgmi-sunday",
    title: "Sunday Scrims: Erangel",
    game: "BGMI",
    gameSlug: "bgmi",
    organizer: "Weekly Local",
    entryType: "FREE",
    entryFee: 0,
    prizePool: 25000,
    currency: "₹",
    participants: 76,
    maxParticipants: 100,
    teamSize: 4,
    format: "Squad · 3 matches",
    date: "31 Aug 2026",
    time: "7:30 PM",
    region: "India · South Asia",
    status: "FILLING_FAST",
    registrationStatus: "AVAILABLE",
    banner: "bgmi",
    accent: "#ffb547",
    registrationDeadline: "31 Aug, 6:30 PM",
    eligibility: ["Age 13+", "India region", "Valid BGMI UID required"],
    rules: ["No cheating, hacks, or exploits", "Use your registered game account", "Organizer decisions follow published rules", "Be respectful in match chat"],
    prizes: [
      { place: "1st place", amount: 12000, label: "₹12,000" },
      { place: "2nd place", amount: 8000, label: "₹8,000" },
      { place: "3rd place", amount: 5000, label: "₹5,000" },
    ],
    schedule: [
      { label: "Registration opens", detail: "27 Aug · 10:00 AM", state: "DONE" },
      { label: "Registration closes", detail: "31 Aug · 6:30 PM", state: "NEXT" },
      { label: "Check-in", detail: "31 Aug · 7:00 PM", state: "LOCKED" },
      { label: "Room details released", detail: "31 Aug · 7:15 PM", state: "LOCKED" },
      { label: "Match starts", detail: "31 Aug · 7:30 PM", state: "LOCKED" },
      { label: "Results published", detail: "31 Aug · 9:15 PM", state: "LOCKED" },
    ],
  },
  {
    id: "wl-freefire-clash",
    title: "Free Fire Clash: Neon District",
    game: "Free Fire",
    gameSlug: "free-fire",
    organizer: "Weekly Local",
    entryType: "PAID",
    entryFee: 49,
    prizePool: 10000,
    currency: "₹",
    participants: 38,
    maxParticipants: 48,
    teamSize: 4,
    format: "Squad · Knockout",
    date: "01 Sep 2026",
    time: "8:00 PM",
    region: "India · South Asia",
    status: "OPEN",
    registrationStatus: "AVAILABLE",
    banner: "free-fire",
    accent: "#ff5c73",
    registrationDeadline: "01 Sep, 7:00 PM",
    eligibility: ["Age 18+", "India region", "Valid Free Fire UID required"],
    rules: ["No account sharing", "No teaming outside the permitted format", "Results are subject to review", "Refunds follow the published cancellation policy"],
    prizes: [
      { place: "1st place", amount: 5000, label: "₹5,000" },
      { place: "2nd place", amount: 3000, label: "₹3,000" },
      { place: "3rd place", amount: 2000, label: "₹2,000" },
    ],
    schedule: [
      { label: "Registration opens", detail: "26 Aug · 12:00 PM", state: "DONE" },
      { label: "Registration closes", detail: "01 Sep · 7:00 PM", state: "NEXT" },
      { label: "Check-in", detail: "01 Sep · 7:30 PM", state: "LOCKED" },
      { label: "Room details released", detail: "01 Sep · 7:45 PM", state: "LOCKED" },
      { label: "Match starts", detail: "01 Sep · 8:00 PM", state: "LOCKED" },
      { label: "Results published", detail: "01 Sep · 10:30 PM", state: "LOCKED" },
    ],
  },
  {
    id: "wl-ludo-lounge",
    title: "Ludo Lounge: Friday Finals",
    game: "Ludo",
    gameSlug: "ludo",
    organizer: "Playfield Club",
    entryType: "FREE",
    entryFee: 0,
    prizePool: 3000,
    currency: "₹",
    participants: 18,
    maxParticipants: 32,
    teamSize: 1,
    format: "Solo · Best of 3",
    date: "04 Sep 2026",
    time: "9:00 PM",
    region: "India · South Asia",
    status: "OPEN",
    registrationStatus: "AVAILABLE",
    banner: "ludo",
    accent: "#8f7cff",
    registrationDeadline: "04 Sep, 8:30 PM",
    eligibility: ["Age 13+", "India region", "Valid Ludo player ID required"],
    rules: ["Use the registered player ID", "No abusive behavior", "One account per player"],
    prizes: [
      { place: "1st place", amount: 1500, label: "₹1,500" },
      { place: "2nd place", amount: 1000, label: "₹1,000" },
      { place: "3rd place", amount: 500, label: "₹500" },
    ],
    schedule: [
      { label: "Registration opens", detail: "28 Aug · 9:00 AM", state: "DONE" },
      { label: "Registration closes", detail: "04 Sep · 8:30 PM", state: "NEXT" },
      { label: "Match starts", detail: "04 Sep · 9:00 PM", state: "LOCKED" },
      { label: "Results published", detail: "04 Sep · 10:30 PM", state: "LOCKED" },
    ],
  },
  {
    id: "wl-bgmi-duo",
    title: "BGMI Duo Rush",
    game: "BGMI",
    gameSlug: "bgmi",
    organizer: "Northside Esports",
    entryType: "PAID",
    entryFee: 99,
    prizePool: 18000,
    currency: "₹",
    participants: 40,
    maxParticipants: 48,
    teamSize: 2,
    format: "Duo · 4 matches",
    date: "06 Sep 2026",
    time: "6:00 PM",
    region: "India · North & West",
    status: "STARTING_SOON",
    registrationStatus: "AVAILABLE",
    banner: "bgmi",
    accent: "#ffb547",
    registrationDeadline: "06 Sep, 5:00 PM",
    eligibility: ["Age 18+", "India region", "Valid BGMI UID required"],
    rules: ["No cheating, hacks, or exploits", "Use your registered game account", "Duplicate registrations will be removed"],
    prizes: [
      { place: "1st place", amount: 9000, label: "₹9,000" },
      { place: "2nd place", amount: 6000, label: "₹6,000" },
      { place: "3rd place", amount: 3000, label: "₹3,000" },
    ],
    schedule: [
      { label: "Registration opens", detail: "25 Aug · 9:00 AM", state: "DONE" },
      { label: "Registration closes", detail: "06 Sep · 5:00 PM", state: "NEXT" },
      { label: "Check-in", detail: "06 Sep · 5:30 PM", state: "LOCKED" },
      { label: "Match starts", detail: "06 Sep · 6:00 PM", state: "LOCKED" },
      { label: "Results published", detail: "06 Sep · 8:45 PM", state: "LOCKED" },
    ],
  },
];

export const dashboardSummary: DashboardSummary = {
  playerName: "Arjun",
  gamerTag: "ARJUNxOP",
  avatar: "A",
  upcomingCount: 2,
  liveCount: 1,
  completedCount: 12,
  totalPoints: 1840,
  nextMatch: {
    tournamentTitle: "Sunday Scrims: Erangel",
    date: "31 Aug 2026",
    time: "7:30 PM",
    status: "Check-in opens in 2h 14m",
  },
};

export const registeredTournaments: RegisteredTournament[] = [
  {
    id: "reg-1001",
    tournamentId: "wl-bgmi-sunday",
    title: "Sunday Scrims: Erangel",
    game: "BGMI",
    registrationId: "WLT-8F2K9",
    date: "31 Aug 2026",
    time: "7:30 PM",
    status: "UPCOMING",
    checkIn: "Not checked in",
    roomDetails: null,
  },
  {
    id: "reg-1002",
    tournamentId: "wl-freefire-clash",
    title: "Free Fire Clash: Neon District",
    game: "Free Fire",
    registrationId: "WLT-4Q7M2",
    date: "24 Aug 2026",
    time: "8:00 PM",
    status: "LIVE",
    checkIn: "Checked in",
    roomDetails: { roomId: "4589021", password: "••••••" },
  },
  {
    id: "reg-1003",
    tournamentId: "wl-ludo-lounge",
    title: "Ludo Lounge: Friday Finals",
    game: "Ludo",
    registrationId: "WLT-1C6P4",
    date: "21 Aug 2026",
    time: "9:00 PM",
    status: "COMPLETED",
    checkIn: "Completed",
    roomDetails: null,
  },
];

export const leaderboard: LeaderboardEntry[] = [
  { rank: 1, player: "KillerRishi", tag: "KR", game: "BGMI", matches: 42, wins: 18, points: 3280, score: 91, trend: "UP", avatar: "KR" },
  { rank: 2, player: "MortalMind", tag: "MM", game: "BGMI", matches: 38, wins: 15, points: 3040, score: 86, trend: "SAME", avatar: "MM" },
  { rank: 3, player: "ARJUNxOP", tag: "AR", game: "BGMI", matches: 35, wins: 13, points: 1840, score: 82, trend: "UP", avatar: "A" },
  { rank: 4, player: "SniperSoul", tag: "SS", game: "Free Fire", matches: 31, wins: 12, points: 1720, score: 77, trend: "DOWN", avatar: "SS" },
  { rank: 5, player: "RushBhai", tag: "RB", game: "Free Fire", matches: 29, wins: 10, points: 1650, score: 72, trend: "UP", avatar: "RB" },
  { rank: 6, player: "LudoLegend", tag: "LL", game: "Ludo", matches: 24, wins: 9, points: 1410, score: 68, trend: "SAME", avatar: "LL" },
];